---
name: GoKart
version: 1.0.0
main: pixelwhiz\gokart\Loader
api: 5.0.0
author: pixelwhiz
website: https://github.com/pixelwhiz/GoKart.git
depend:
  - EconomyAPI
src-namespace-prefix: pixelwhiz\gokart
permissions:
  gokart.cmd:
    default: true
    description: Allows players to use the /gokart command.
...
